<a href="https://colab.research.google.com/github/omareldalil4/Transformers/blob/main/Transformers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn.functional as F
import math

def self_attention(input_sentence):
    """Compute self-attention for a given input sentence"""

    tokens = input_sentence.split()
    print(f"Tokens: {tokens}")

    embedding_dim = 4
    vocab_size = len(tokens)


    embeddings = torch.randn(len(tokens), embedding_dim)
    print(f"\nEmbeddings:\n{embeddings}")


    positions = torch.arange(len(tokens)).unsqueeze(1)
    position_enc = torch.zeros(len(tokens), embedding_dim)

    for pos in range(len(tokens)):
        for i in range(0, embedding_dim, 2):
            position_enc[pos, i] = math.sin(pos / (10000 ** ((2 * i)/embedding_dim)))
            if i+1 < embedding_dim:
                position_enc[pos, i+1] = math.cos(pos / (10000 ** ((2 * (i+1))/embedding_dim)))

    print(f"\nPositional Encodings:\n{position_enc}")

    X = embeddings + position_enc
    print(f"\nInput with Positional Encoding (X):\n{X}")


    d_k = embedding_dim
    W_Q = torch.randn(embedding_dim, embedding_dim)
    W_K = torch.randn(embedding_dim, embedding_dim)
    W_V = torch.randn(embedding_dim, embedding_dim)

    print(f"\nWeight Matrices:")
    print(f"W_Q:\n{W_Q}")
    print(f"W_K:\n{W_K}")
    print(f"W_V:\n{W_V}")


    Q = torch.matmul(X, W_Q)
    K = torch.matmul(X, W_K)
    V = torch.matmul(X, W_V)

    print(f"\nQuery Matrix (Q):\n{Q}")
    print(f"Key Matrix (K):\n{K}")
    print(f"Value Matrix (V):\n{V}")


    attention_scores = torch.matmul(Q, K.transpose(-2, -1)) / math.sqrt(d_k)
    print(f"\nRaw Attention Scores:\n{attention_scores}")


    attention_weights = F.softmax(attention_scores, dim=-1)
    print(f"\nAttention Weights (after softmax):\n{attention_weights}")


    output = torch.matmul(attention_weights, V)
    print(f"\nOutput:\n{output}")

    return output, attention_weights


input_sentence = "What are the symptoms of diabetes"
output, attn_weights = self_attention(input_sentence)

Tokens: ['What', 'are', 'the', 'symptoms', 'of', 'diabetes']

Embeddings:
tensor([[-1.6928, -0.8235, -1.6247, -0.7604],
        [-0.7562,  1.2801,  0.0201,  0.8880],
        [ 1.2130,  1.1126,  1.3241,  0.7374],
        [-0.5092,  1.1380, -2.3743,  0.5405],
        [ 0.0657,  1.1266, -0.8109,  0.4358],
        [-0.1330,  1.1831, -0.6830, -0.3501]])

Positional Encodings:
tensor([[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00],
        [ 8.4147e-01,  9.9995e-01,  1.0000e-04,  1.0000e+00],
        [ 9.0930e-01,  9.9980e-01,  2.0000e-04,  1.0000e+00],
        [ 1.4112e-01,  9.9955e-01,  3.0000e-04,  1.0000e+00],
        [-7.5680e-01,  9.9920e-01,  4.0000e-04,  1.0000e+00],
        [-9.5892e-01,  9.9875e-01,  5.0000e-04,  1.0000e+00]])

Input with Positional Encoding (X):
tensor([[-1.6928,  0.1765, -1.6247,  0.2396],
        [ 0.0853,  2.2801,  0.0202,  1.8880],
        [ 2.1223,  2.1124,  1.3243,  1.7374],
        [-0.3681,  2.1375, -2.3740,  1.5405],
        [-0.6911,  2.1258, -0.81